{{- $namespace := .Values.OverrideNamespace -}}

{{- with .Values.configMap }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Namespace $namespace }}
data:
  {{- range $key, $value := .data }}
    {{ $key }}: '{{ $value }}'
  {{- end }}
{{- end }}
{{- end }}