{{- with .Values.pvc }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  resources:
    requests:
      storage: {{ .size }}
  volumeMode: {{ .volumeMode }}
  accessModes:
  {{- range $value := .accessModes }}
    - {{ $value }}
  {{- end }}
  storageClassName: {{ .storageClassName }}
{{- end }}
{{- end }}