{{- $namespace := .Values.OverrideNamespace -}}

{{- with .Values.secret }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Namespace $namespace }}
type: {{ .type }}
data:
  {{- range $key, $value := .data }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}