{{- $namespace := .Values.OverrideNamespace -}}

{{- with .Values.serviceAccount }}
{{- if .enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Namespace $namespace }}
  annotations:
  {{- range $key, $value := .annotations }}
    {{ $key }}: '{{ $value }}'
  {{- end }}
{{- end }}
{{- end }}